apiVersion: v1
kind: Service
metadata:
  name: inventory-manager-service
  labels:
    app: inventory
spec:
  type: NodePort
  selector:
    app: inventory
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30080   # You can change this if you want another port
